name: Core production deploy

on:
  push:
    branches:
      - core-release

  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-hongkong
  REGISTRY: registry.cn-hongkong.aliyuncs.com
  NAMESPACE: zkip
  IMAGE: noz-core
  TAG: ${{ github.sha }}

jobs:
  ready:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Debug
        run: echo "Core Production':' $TAG"
        